// eslint-disable-next-line no-undef
define([], function () {
  return {
    Command1: "Command 1",
    CommandSignDocumentsTitle: "Sign Documents",
    signatureFormUseForAllLabel: "Use the same signature for all documents",
    signatureFormImageLabel: "Select the signature image",
    signatureFormReasonLabel: "Reason for signing",
    signatureFormLocationLabel: "Signing location",
    signatureFormRectLabel: "Signature placement",
    signatureFormAllDocuments: "All documents",
    signatureFormTitle: "Document signature properties",
    signatureFormSelectPosition: "Select signature placement",
    continueButton: "Continue",
    cancelButton: "Cancel",
    signatureSingleTitle: "Single document signature properties",
    signaturePlacementHint: "Place the signature on the document",
    signatureModalPrevious: "Previous",
    signatureModalNext: "Next",
    signatureModalClose: "Close",
    signatureModalFileTitlePrefix: "File signature:",
    fileFieldInvalidImage: "Please select a valid PNG or JPEG image.",
    fileFieldPreviewLabel: "Preview",
    fileFieldPreviewAlt: "Selected signature preview",
    progressLabelPrefix: "Signing in progress:",
    progressDescription: "Please wait",
    pdfPreviewLoading: "Loading PDF...",
    signingTitle: "Document signing",
    selectedFilesLabel: "Selected files:",
    victoryTitle: "Successfully signed",
    closeWindow: "Close window",
    publicKeyUnavailable: "Public key is not available.",
    signingUnknownError: "Unexpected error while signing.",
    validFilesLabel: "Validity check:",
    fileFieldInvalidSize: "The selected file exceeds the maximum size of 1 MB.",
  };
});
