declare interface ISignPdfStrings {
  Command1: string;
  CommandSignDocumentsTitle: string;
  signatureFormUseForAllLabel: string;
  signatureFormUseForAllLabelNoPublicKey: string;
  signatureFormImageLabel: string;
  signatureFormReasonLabel: string;
  signatureFormLocationLabel: string;
  signatureFormRectLabel: string;
  signatureFormAllDocuments: string;
  signatureFormTitle: string;
  signatureFormSelectPosition: string;
  signatureFormUseAttachmentFromRow: string;
  signatureFormAttachmentColumnLabel: string;
  signatureFormAttachmentColumnPlaceholder: string;
  signatureFormAttachmentColumnMissing: string;
  continueButton: string;
  cancelButton: string;
  signatureSingleTitle: string;
  signaturePlacementHint: string;
  signatureModalPrevious: string;
  signatureModalNext: string;
  signatureModalClose: string;
  signatureModalFileTitlePrefix: string;
  fileFieldInvalidImage: string;
  fileFieldPreviewLabel: string;
  fileFieldPreviewAlt: string;
  progressLabelPrefix: string;
  progressDescription: string;
  pdfPreviewLoading: string;
  signingTitle: string;
  selectedFilesLabel: string;
  victoryTitle: string;
  closeWindow: string;
  publicKeyUnavailable: string;
  validFilesLabel: string;
  signingUnknownError: string;
  fileFieldInvalidSize: string;
  pickCertificateOrSeparator: string;
  pickCertificateSkipButton: string;
  pickCertificateSkipDescription: string;
  pickCertificateTitle: string;
  pickCertificateDescription: string;
  pickCertificateOptionCertificateTitle: string;
  pickCertificateOptionCertificateDescription: string;
  pickCertificateOptionTsaTitle: string;
  pickCertificateOptionTsaDescription: string;
  pickCertificateBackButton: string;
  attachmentUploadLabel: string;
  attachmentOverrideInfo: string;
  attachmentOptionalInfo: string;
  attachmentFieldInvalidSize: string;
  attachmentFieldButtonLabel: string;
  attachmentFieldSelectedFilePrefix: string;
}

declare module "SignPdfStrings" {
  const strings: ISignPdfStrings;
  export = strings;
}
